### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by egorky** [jrCleber/call-service-whatsapp#1]
Hi, how is this different from Whaticket or Press-ticket?  https://github.com/FilipeCamillo/Press-Ticket

**Comment by jrCleber** [comment]
> Hi, how is this different from Whaticket or Press-ticket? https://github.com/FilipeCamillo/Press-Ticket



Good morning! This code performs an automated service. The customer contacts the connected number, selects the category (financial, commercial, …) created by you and starts a conversation with the available attendant.
